### PR TITLE
Update to ebible.py

### PR DESCRIPTION
**Pull request by SirBac0n**
A new version of ebible.py along with a helper file vrs_diffs.yaml to help with guessing versifications. Also, some basic tests and test_ebible.py added in the tests folder

### CODE REVIEW

**Review by davidbaines — APPROVED** [review]
I'm not very familar with reviewing code. The changes to ebible.py look like good improvements. Many of the changes are for more tests and better logging. 
Looks good to me.

**Comment by jcuenod** [comment]
I know this is now merged, but the previous version of `ebible.py` had a relatively detailed comment at the top of the file detailing what it did. It seems like a regression to lose that information and to also not have checklist in this PR ensuring that any of that functionality is not lost.

Was this PR requested by someone? If not, it's worth noting that anyone who uses this repo may expect particular behaviour/functionality, and there are too many changes here to quickly assess whether changes in that regard may be a concern.

This is not meant as a critique to anyone, I'm just flagging a potential issue.

**Comment by davidbaines** [comment]
This is a helpful critique, as I'm not familiar with good processes of
using github.  Perhaps we can undo what I've done and take the time to
review the changes?

**Comment by SirBac0n** [comment]
That is a very helpful critique, thank you for pointing that out. I am working on getting things back to the way they were with some modifications to settings_file.py. It should work the same just with a slightly different implementation for guessing the versification. I should have a pull request up by the end of the day

**Pull request merged**
