### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by meschw04**
Adding the CC-BY-NC-ND license.

### CODE REVIEW

**Review by DCNemesis — APPROVED** [review]
License is needed for our content. This is the most restrictive. We should also update the README to clarify that some material may be less than the overall license and can still be used (like SA and public domain material)

**Comment by joelthe1** [comment]
This does not accurately represent the state of the repository. We have a mix of content some of which are less restrictive than others. It was for this reason that we have the [licenses directory](https://github.com/BibleNLP/ebible/tree/169af6cd6778b52095032eeda7cf606a07a0f4fd/metadata/licences) as a poor-man's solution. But I agree we need more documentation to clarify the nuances. However, this PR does not serve that purpose.

**Comment by DCNemesis** [comment]
@joelthe1 the licenses directory is authoritative on licenses, but if the licenses aren't marked in a machine readable format, it makes it much easier to abuse by crawling. We can clarify in the README for human readers.

**Comment by joelthe1** [comment]
Agreed. I think though that we should revert this PR change.

**Comment by DCNemesis** [comment]
You mean until we've clarified the README?

**Comment by joelthe1** [comment]
> You mean until we've clarified the README?

This change makes it look like the whole repository is under the CC BY-NC-ND, which is not the case.

**Pull request merged**
